Script started on 2022-01-26 13:06:20-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ gcc -g -Wall.c[K[K ascii.c -o ass[Kcii
[?2004l[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ -[K./ascii 
[?2004lSurprised Pikachu the Meme, for those who browse reddit on the linux terminal:
----------------------------------------------------------------------------------------------
   #                                                                            #
  ###                                                                          ###
  #####                                                                       #####
  ####  #                   #########################                        ###  #
   ##    #          ##################         ##################           ##    #
    #     #      #########                                 #########       #     #
     #     #    ###                                               ###     #     #
      #     ## ###      #                              #             ### ##     #
       #      #      #  ##                          #  ##               #      #
        #            #####                          #####                     #
       # ##            ##                             ##                    ## #
      #                             #####                                      #
     #                               ####                                       #
     # $$$$                                                                 $$$$ #
    #$$$$$$$                       #########                               $$$$$$$$#
   #$$$$$$$$                      #$$$$$$$$$#                               $$$$$$$$#
  #$$$$$$$$                       #$$$$$$$$$#                                $$$$$$$#
  #$$$$$$$                        #$$$$$$$$$#                                 $$$$$$$#
 # $$$$$$                          #########                                    $$$$$ #
#                                                                                      #
#                                                                                      #
#                                                                                       #
 #                                                                                       #
  #                                                                                       #
   #                                                                                       #
    ##                                                                                       #
----------------------------------------------------------------------------------------------
If it the lines don't look mostly smooth it or have gaps the terminal needs to be a bigger window.
[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ [K]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ [K]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ exit
[?2004lexit

Script done on 2022-01-26 13:07:06-07:00 [COMMAND_EXIT_CODE="0"]
