Script started on 2022-01-26 10:00:11-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ gcc -g -Wall hello.c -o hello
[?2004l[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ ./hello 
[?2004lHello World!
[?2004h]0;kas@pop-os: ~/CSE 113/labs/lab0[01;32mkas@pop-os[00m:[01;34m~/CSE 113/labs/lab0[00m$ exit
[?2004lexit

Script done on 2022-01-26 10:00:35-07:00 [COMMAND_EXIT_CODE="0"]
